project_id = "yrjwyeuqfleqhbveohrf"

[functions.php-api-proxy]
verify_jwt = false

[functions.profesor-virtual]
verify_jwt = false

[functions.generar-tecnica]
verify_jwt = false

[functions.extraer-texto]
verify_jwt = false

[functions.generar-resumen]
verify_jwt = false

[functions.generar-plan-estudio]
verify_jwt = false

[functions.generar-descripcion-plan]
verify_jwt = false

[functions.generar-plan-automatico]
verify_jwt = false

[functions.guardar-plan-generado]
verify_jwt = false

[functions.enviar-recordatorio-plan]
verify_jwt = false

[functions.generar-plan-fisico]
verify_jwt = false

[functions.guardar-plan-fisico]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.create-donation-payment]
verify_jwt = false

[functions.generar-preguntas-ia]
verify_jwt = false

[functions.generar-psicotecnicos-ia]
verify_jwt = false

[functions.fetch-international-news]
verify_jwt = false

[functions.enviar-recordatorio-flashcards]
verify_jwt = false

[functions.analizar-plato]
verify_jwt = false
